### ISSUE TITLE
Sometimes the build goes in timeout because of an exception

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#739] opened 2021-04-29 21:16 UTC
Occasionaly, builds with Db2 fail because [of a bug in the Vert.x Db2 client](https://github.com/eclipse-vertx/vertx-sql-client/issues/920). This bug has been already fixed and it should disappear when we will upgrade to Vert.x 4.1.

The problem is that, when it happens, our build get stuck and goes in timeout, even if a real error happened.
I suspect we are swallowing an exception somewhere in one of the classes related to the connection. 

An example of this behaviour is at this commit: d3d46c4f63fe227558a46028d3cfbf2661759ed0
The build will get stuck on Db2:
```
./gradlew clean testDbDb2
```

The real exception is visible setting  `showStandardStreams = true` in the gradle build.

**Comment by gavinking** [comment] 2021-04-29 21:22
I mean, it *should* be pretty straightforward to write a test to check what happens with exceptions coming from the driver; just send some broken SQL and see what happens.

**Comment by DavideD** [comment] 2021-04-29 21:29
I wonder if this happens because of a bug in the Db2 client. But I haven't dedicated much time and you can test yourself and see that a broken SQL won't block the build. Until not when I've tried. Maybe you have somethiing different in mind?

**Comment by gavinking** [comment] 2021-04-29 21:45
Well that's what I'm getting at: I feel like it's more likely to be a bug in the driver) or possibly in our test suite infrastructure) than it is to be a bug in HR. But of course that's no more than speculation on my part.

**Comment by gbadner** [comment] 2021-04-30 23:21
I'm seeing a timeout due to Vert.x throwing `NoClassDefFoundError` using 4.1.0-SNAPSHOT. I mentioned this in https://github.com/hibernate/hibernate-reactive/pull/741#issuecomment-830451644.

**Comment by gavinking** [comment] 2021-05-25 10:24
>  I feel like it's more likely to be a bug in the driver

I've now confirmed this.

We are never receiving this exception, which gets swallowed somewhere deep inside Vert.x.

I think we should close this issue: we don't need to have an issue open against HR for every bug in the Vert.x driver.

(In this case, we currently have *three* issues open against HR for *one* bug in the Vert.x DB2 driver. That's excessive.)

**Closed by gavinking** 2021-05-25 10:24 UTC
Labels: problem
