### ISSUE TITLE
Trying to run hibernate calls on reactive(parallel) but getting NoSuchElementException

### ISSUE THREAD

**Issue by ozkanpakdil** [hibernate/hibernate-reactive#1615] opened 2023-05-02 21:02 UTC
I ask [this question](https://github.com/smallrye/smallrye-mutiny/issues/1267) first on smallrye, and @jponge said this is hibernate question. 

I stumbled to this question on stackoverflow https://stackoverflow.com/questions/76072695/how-can-i-reactive-list-entities-with-different-params-in-quarkus-3-0-0-rc2-with/76101341 which is complaining about **NoSuchElementException** or **IllegalStateException: Session/EntityManager is closed**, from code below
```java
    return Uni.combine().all().unis(dogs, cats, rats, dolphins).asTuple().map(animal -> {
      summary.setDogs(animal.getItem1());
      summary.setCats(animal.getItem2());
      summary.setRats(animal.getItem3());
      summary.setDolphins(animal.getItem4());
      return summary;
    });
```
I tried to read through [all docs](https://smallrye.io/smallrye-mutiny/2.2.0/guides/combining-items/) and solve the issue but could not find a proper solution but @Lukec1 who open the question found a solution,

```java
 return dogs.invoke(summary::setDogs)
    .chain(() -> cats.invoke(summary::setCats))
    .chain(() -> rats.invoke(summary::setRats))
    .chain(() -> dolphins.invoke(summary::setDolphins))
    .replaceWith(summary);
```
which looks like not really running on parallel/async/reactive. so my question is "are there anyway to run hibernate reactive run queries on parallel in one jvm"

here is the reproducer https://github.com/Lukec1/quarkus-3.0.0.CR2-sample and hit http://localhost:8080/zoo/animals/Melani

thanks in advance.

**Comment by DavideD** [comment] 2023-05-03 07:52
The problem is that Hibernate Reactive needs operations on the database to happen in a predictable order to avoid errors when managing entities.  So, you cannot share the same session among different threads or uni streams.

We don't have a solution for this at the moment, and chaining the uni is the only way to be sure that everything will work as expected.

I'm going to close this issue because this is a known limitation, but feel free to continue the conversation if you have more questions.

**Closed by DavideD** 2023-05-03 07:52 UTC
