### ISSUE TITLE
Cannot execute CompletableFuture inside withSession or withTransaction workflow 

### ISSUE THREAD

**Issue by tiagomistral** [hibernate/hibernate-reactive#1194] opened 2022-02-10 17:52 UTC
Hello,

I'm trying to execute a completable future inside a mutiny withSession and I get (sometimes, many times) the error message `Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread: 'vert.x-eventloop-thread-3' current Thread`

The code to reproduce is below. I'm trying to propagate the thread executor but it don't work.

    @Inject
    Mutiny.SessionFactory mutinySessionFactory;
    
    @Inject 
    ManagedExecutor managedExecutor;
    
    @GET
    @Path("test")
    public Uni<String> test() throws ExecutionException, InterruptedException {
        return mutinySessionFactory.withSession(session -> {
            return Uni
            .createFrom().completionStage(
                    CompletableFuture.supplyAsync(() -> "hello", managedExecutor)
            );
        });
    }

The error stack trace:

> java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread: 'vert.x-eventloop-thread-3' current Thread: 'executor-thread-0'
	at org.hibernate.reactive.common.InternalStateAssertions.assertCurrentThreadMatches(InternalStateAssertions.java:46)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.threadCheck(ReactiveSessionImpl.java:154)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.checkOpen(ReactiveSessionImpl.java:1556)
	at org.hibernate.internal.AbstractSharedSessionContract.checkOpenOrWaitingForAutoClose(AbstractSharedSessionContract.java:399)
	at org.hibernate.internal.SessionImpl.closeWithoutOpenChecks(SessionImpl.java:429)
	at org.hibernate.internal.SessionImpl.close(SessionImpl.java:416)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.reactiveClose(ReactiveSessionImpl.java:1489)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at org.hibernate.reactive.context.impl.VertxContext.execute(VertxContext.java:69)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.subscribe(UniRunSubscribeOn.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureConsume$UniOnItemOrFailureConsumeProcessor.onItem(UniOnItemOrFailureConsume.java:37)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

There's any way to force the completable future to use allways the current thread?

**Comment by DavideD** [comment] 2022-02-10 20:41
At first glance, I'd say the problem is that you are using `supplyAsync`, what are you trying to achieve here?

**Comment by tiagomistral** [comment] 2022-02-11 08:13
Hey @DavideD 

I'm using the `CompletableFuture.supplyAsync` just for simplify my use case.

My real use case is that I need to update an object from the database and if something change related with an attachment delete it using `software.amazon.awssdk.services.s3.S3AsyncClient.deleteObjects`.

**Comment by DavideD** [comment] 2022-02-11 10:18
The problem is that the session is not thread-safe and needs to run in an even-loop-thread.
You are basically trying to use it in a thread that's not the one it has been created and so you see the error. Right now it only happens when the session get closed but you would see it sooner if you actually try to use the session in that block. It's also not going to be an event-loop-thread.

Why do you need to use supplyAsync to call `S3AsyncClient.deleteObjects` (I'm not familiar with the API). Or is the S3 client that uses supplyAsync?

**Comment by gavinking** [comment] 2022-02-11 10:39
Remember that problems like these can usually be solved by creating a new dedicated session for each thread. They arise only when you try to share a session across threads, which is simply an incorrect thing to do.

**Comment by tiagomistral** [comment] 2022-02-11 13:24
Sry @DavideD maybe I was not clear

I don't use the supplyAsync to call the `S3AsyncClient.deleteObjects`but this call is already async and sometimes use a different even-loop.thread which causes the error :P 

With the following I cannot reproduce the error anymore:

    @Inject
    Mutiny.SessionFactory mutinySessionFactory;

    @Inject 
    Vertx vertx;

    @GET
    @Path("test")
    public Uni<String> test() throws ExecutionException, InterruptedException {
        return mutinySessionFactory.withSession(session -> {
            return Uni
            .createFrom().completionStage(
                    CompletableFuture.supplyAsync(() -> "hello", MutinyHelper.executor(vertx))
            );
        });
    }

Can you validate if this solution is the correct/best approach?

**Comment by DavideD** [comment] 2022-02-11 13:57
Yes, I guess that could work.
You could also do this:

```
        import org.hibernate.reactive.common.spi.Implementor;

	@GET
	@Path("test")
	public Uni<String> test() {
		return sf.withSession( session -> {
			return Uni.createFrom()
					.completionStage( CompletableFuture.supplyAsync( () -> "hello", ( (Implementor) sf ).getContext() ) );
		} );
	}

```

But I need to think a bit more about this

**Comment by Sanne** [comment] 2022-02-11 14:35
in your error message above it's stating that it's being run on `executor-thread-0`. Clearly that's not a vert.x thread, which is illegal. I'm glad our checks caught the error as otherwise you'd get into deeper trouble.

You need to ensure operations happen in these conditions:

1.  on a vert.x thread (on the vert.x eventloop)
2. stay on the same thread for the whole stream

To be clear by "operations" I mean any sequence of operations which starts by opening a session or starting a transaction, does things within such session, and then closes this session / commits this transaction.

There should be no need to use executors or other threads as this is running on a non-blocking reactive chain so you can't achieve much by parallelizing.

IFF on the other hand you need to block or invoke blocking APIs, you can do so but need to ensure you wait for such completion (without blocking the reactive threads) and then *return* on the reactive threads to finish the operations when you're done. You can't use Hibernate Reactive while your scope is being executed on the blocking thread.

**Comment by Sanne** [comment] 2022-02-11 14:36
(I'm closing it as it's not an issue but feel free to keep talking about it here)

**Closed by Sanne** 2022-02-11 14:35 UTC

**Comment by Sanne** [comment] 2022-02-11 14:41
P.S. I'm also not familiar with the S3 client, but your use case seems valid - just needs to be integrated with Hibernate Reactive in a different way, as the code you show above is a violation of H.R.'s requirements.

It might help to provide a more complete reproducer, but report it to the Quarkus team as this doesn't seem a problem of H.R.
(I'm guessing that's Quarkus from what I see?)

**Comment by tiagomistral** [comment] 2022-02-12 11:43
Hey @Sanne 

You are right I'm using the Quarkus framework.

I'm not completely sure about if I am or I am not doing something wrong here, but I will leave here my current solution for you guys give me your opinion :)

Thanks in advance


    
    @ConfigProperty(name = "quarkus.s3.aws.credentials.static-provider.access-key-id")
    private String accessKeyId;

    @ConfigProperty(name = "quarkus.s3.aws.credentials.static-provider.secret-access-key")
    private String secretAccessKey;

    @ConfigProperty(name = "quarkus.s3.aws.region")
    private String region;

    @Inject
    Mutiny.SessionFactory mutinySessionFactory;
    
    @Inject
    private Vertx vertx;

    @GET
    @Path("test")
    public Uni<Object> test() throws ExecutionException, InterruptedException {
        
        S3AsyncClient s3 = S3AsyncClient.builder()
                .region(Region.of(region))
                .credentialsProvider(() -> AwsBasicCredentials.create(accessKeyId, secretAccessKey))
                .asyncConfiguration(b -> b.advancedOption(SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR,
                        MutinyHelper.executor(vertx.getOrCreateContext())))
                .build();
        
        List<String> attachmentIds = List.of("attachmentId");
        
        // Create an Object identifier to identify the file to be deleted
        ArrayList<ObjectIdentifier> toDelete = new ArrayList<>();
        attachmentIds.forEach(attachmentId -> toDelete.add(ObjectIdentifier.builder().key(attachmentId).build()));

        // Create a Delete object with the object identified
        Delete delete = Delete.builder().objects(toDelete).build();

        // Delete the object
        DeleteObjectsRequest deleteObjectsRequest = DeleteObjectsRequest.builder()
                .bucket("bucketName")
                .delete(delete)
                .build();
        
        return mutinySessionFactory.withSession(session -> {
            return Uni
            .createFrom().completionStage(
                    s3.deleteObjects(deleteObjectsRequest));
        });
    }

**Comment by DavideD** [comment] 2022-02-14 13:37
I think this is the correct approach. [From the API](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/client/config/SdkAdvancedAsyncClientOption.html), the S3 async client would use a `ThreadPoolExecutor` as default otherwise.

A couple of things worth mentioning:

* `getOrCreateContext` will create an new context if one doesn't exist. It should never be the case but you might want to replace it with `Vertx.currentContext` because a new context create that way would cause issues hard to debug
* Or, instead, you  could get the correct executor via:
  ```
  Executor executor = ( (Implementor) mutinySessionFactory ).getContext();
  ```
  This should be equivalent to MutinyHelper.executor(`Vertx.currentContext)` in this case. But, if not, the executor returned by the factory will have additional checks to make sure that everything is fine. Plus, you don't need to inject an instance of Vert.x.

Anyway, up to you.

**Comment by tiagomistral** [comment] 2022-02-14 15:27
Thanks @DavideD I will use it like you suggest ;)

Hope this can help the community 👍
