### ISSUE TITLE
Unexpected access to the database when query cache is enabled

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#298] opened 2020-07-28 10:49 UTC
When a query is cachable but the entities in the result aren't cached, the following  error occurs:

```
Unexpected access to the database
org.hibernate.AssertionFailure: Unexpected access to the database
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.onLoad(DefaultReactiveLoadEventListener.java:102)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:113)
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1184)
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1049)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.internalLoad(ReactiveSessionImpl.java:148)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:697)
```

**Comment by DavideD** [comment] 2020-07-28 10:50
I've already created a test case for this and I'm checking if we can fix it without too much trouble

**Comment by DavideD** [comment] 2020-07-28 10:51
If anything, this should be at least a `LazyInitializationException`

**Comment by gavinking** [comment] 2020-07-31 17:42
Probably this should have been done under #247.

**Comment by gavinking** [comment] 2020-08-03 09:25
@DavideD I'm closing this issue because it's essentially a dupe of #247. 

(But I've copied the new information into that issue.)

**Closed by gavinking** 2020-08-03 09:25 UTC
Labels: bug

**Comment by DavideD** [comment] 2020-08-03 09:29
ok, thanks
