### ISSUE TITLE
java.lang.IllegalStateException: Session/EntityManager is closed

### ISSUE THREAD

**Issue by Jotschi** [hibernate/hibernate-reactive#1073] opened 2021-12-03 09:55 UTC
I'm currently writing a [PoC for Hibernate Reactive + Vert.x](https://github.com/metaloom/poc-vertx-hibernate) and encountered an issue when loading data. I see `Session/EntityManager is closed` whenever I concurrently access the REST API.

I was also able to reproduce the issue in the boiler plate howto application from Vert.x.

## Steps to reproduce

* Import and run: https://github.com/vertx-howtos/hibernate-reactive-howto
* Create one product via 
 ```
POST http://localhost:8080/products
{
	"name": "test",
	"price": 0
}
```
* Run `wrk -d 10s -c 20 http://localhost:8080/products/1`
* Observe the errors in the server log

## Stacktrace 

* https://gist.github.com/Jotschi/d82e906ecde9db4b2f2232306cff5c26

## Notes

I have tried to [create reproducer tests](https://github.com/Jotschi/hibernate-reactive-howto/tree/reproducers/src/test/java/io/vertx/howtos/hr) for this which do not require the use of `wrk` but so far it has proven hard to reliably reproduce the fault with a test.

Bumping the hibernate reactive dependency in the howto project to 1.1.0.Final did not affect the issue.

The example uses `persist(product).call(session::flush)` the javadoc states to use `#map`. I'm not that familiar with Mutiny and not sure whether both equivalent.

**Comment by DavideD** [comment] 2021-12-03 10:23
I'm having a look but the fact that the session is closed makes me think that something hasn't been chain correctly in the stream.

**Comment by DavideD** [comment] 2021-12-03 10:28
>  persist(product).call(session::flush)

yes, this is correct

**Comment by DavideD** [comment] 2021-12-03 11:34
> I'm having a look but the fact that the session is closed makes me think that something hasn't been chain correctly in the stream.

Nevermind, this is something else

**Comment by markusdlugi** [comment] 2021-12-09 09:41
Hi @Jotschi, can you maybe try to set the HR version in your project to 1.0.0.CR9 and check if the problem still happens there?

We're seeing similar issues in our applications where HR will often throw such errors when things happen concurrently, but only in Quarkus 2.4.2.Final (which uses HR 1.0.1.Final). In Quarkus 2.3.1.Final (using HR 1.0.0.CR9) everything's working perfectly fine for us.

If the behavior's the same for @Jotschi, I guess some change in between those versions must be responsible for the problems, right, @DavideD? ORM is only one revision apart in both Quarkus versions (5.6.1.Final vs. 5.6.0.Final).

**Comment by DavideD** [comment] 2021-12-09 09:57
I will check later but I guess it's possible

**Comment by Jotschi** [comment] 2021-12-09 10:15
@markusdlugi The project is the official Vert.x hibernate reactive howto. I tested your suggested changes:

It seems the dependencies are not compatible. If I switch to 1.0.0.CR9 I get a NoSuchMethodError. 
I tested mutiny-vertx 2.14.2 (Vert.x 4.1.5) and 2.16.0 (Vert.x 4.2.1)
```java
java.lang.NoSuchMethodError: 'void io.vertx.core.net.impl.pool.ConnectionPool.acquire(io.vertx.core.impl.EventLoopContext, io.vertx.core.net.impl.pool.PoolWaiter$Listener, int, io.vertx.core.Handler)'
```
What Vert.x version are you suggesting? I can try to select the matching Vert.x version and report back to you.

**Comment by markusdlugi** [comment] 2021-12-09 10:20
@Jotschi, Quarkus version 2.3.1.Final uses Vert.x 4.1.4 and mutiny-vertx 2.13.0

**Comment by Jotschi** [comment] 2021-12-09 10:35
@markusdlugi With mutiny-vertx 2.13.0 and HR 1.0.0.CR9 I don't see the error.

**Comment by markusdlugi** [comment] 2021-12-09 10:44
@Jotschi, great, thanks for the investigation :)

@DavideD, that should hopefully narrow it down quite a lot, right? So the problem was most likely introduced with either CR10 or Final:
https://github.com/hibernate/hibernate-reactive/milestone/12?closed=1
https://github.com/hibernate/hibernate-reactive/milestone/13?closed=1

**Comment by DavideD** [comment] 2021-12-09 11:47
Thanks for investigating.
I have the feeling that's related to this issue: https://github.com/hibernate/hibernate-reactive/issues/950

**Comment by hantsy** [comment] 2021-12-21 12:09
My Hibernate reactive + Vertx example: https://github.com/hantsy/vertx-sandbox/tree/master/mutiny-spring-hibernate, but not encountered this issue.

**Comment by gavinking** [comment] 2022-01-07 12:56
> Thanks for investigating.
> I have the feeling that's related to this issue: #950

@DavideD I don't understand your comment here. WDYM?

**Comment by DavideD** [comment] 2022-01-07 13:36
That's the most involved change between CR9 and CR10. So it might be related to it. That's all

**Comment by markusdlugi** [comment] 2022-01-10 13:45
@DavideD I tested it with the reproducer provided by @Jotschi and the issue was actually introduced with 1.0.0.Final. Version CR10 is still working fine, no errors whatsoever. Once you switch the reproducer to Final, the issue happens even with the smallest bit of concurrency and is actually really bad. For example:

```
 ~ wrk -d 10s -c 20 http://localhost:8080/products/1
Running 10s test @ http://localhost:8080/products/1
  2 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   184.41ms   51.43ms 528.58ms   90.26%
    Req/Sec    57.00     27.67   101.00     64.61%
  1090 requests in 10.03s, 85.73KB read
  Non-2xx or 3xx responses: 1028
Requests/sec:    108.65
Transfer/sec:      8.55KB
```

So even with just 2 concurrent threads, 1028/1090 requests failed due to this issue, so like a 94% failure rate. Using HR CR9 or CR10, not a single request fails.

I don't have deep knowledge of your code, but if the problem was introduced with 1.0.0.Final then I think only the following change could possibly cause this, right? https://github.com/hibernate/hibernate-reactive/issues/1001

**Comment by markusdlugi** [comment] 2022-01-10 13:49
And by the way, the latest release 1.1.1.Final is also still affected by this problem. Needless to say, it's not really usable with this rate of errors.

**Comment by DavideD** [comment] 2022-01-10 14:00
I will check this issue this week

**Comment by DavideD** [comment] 2022-01-11 13:43
@markusdlugi I've just tested this and if I revert #1001 everything works

**Comment by DavideD** [comment] 2022-01-11 18:56
@markusdlugi It seems that applying this PR also fix the issue: https://github.com/hibernate/hibernate-reactive/pull/1118

I'm prone to say that this is the right fix but I'm not sure what's the difference between local and non local data in a Context.
I will continue tomorrow.

**Comment by markusdlugi** [comment] 2022-01-11 19:06
@DavideD Thanks a lot for investigating! I can also test tomorrow with a more complex application in case you need more feedback on this.

**Comment by gavinking** [comment] 2022-01-11 19:50
@DavideD the difference is that the local context is local to the particular "logical thread" whereas there is one (non-local) `Context` per verticle.

**Comment by DavideD** [comment] 2022-01-12 07:08
> @DavideD Thanks a lot for investigating! I can also test tomorrow with a more complex application in case you need more feedback on this.

More testing and feedback is always appreciated

**Comment by DavideD** [comment] 2022-01-12 12:37
Any idea how I can unit test this?

**Comment by gavinking** [comment] 2022-01-13 17:09
I'm certain that @Sanne's right, and this problem was a consequence of #948. The Vert.x context and the Vert.x local context are _very_ different things&mdash;kinda like the difference between a static variable and a threadlocal&mdash;and if we mix them up then obviously everything goes haywire.

I think we need to prioritize an immediate release just to fix this. Because right now anyone who uses `withTransaction()` or `withSession()` has a completely broken program.

**Comment by gavinking** [comment] 2022-01-13 17:10
(P.S. sorry for being slow to pick up on this, I was very busy recently with the other Hibernate which is doing a major release very soon.)

**Comment by DavideD** [comment] 2022-01-13 17:23
We are working on this. I haven't merge the fix yet because I want to have a test in Hibernate Reactive for this.
I've almost finished writing one that should work for the time being

**Comment by DavideD** [comment] 2022-01-13 17:28
Reopening this issue because the PR doesn't have a test

**Comment by DavideD** [comment] 2022-01-14 09:39
It should be fixed now.
Thanks a lot @Jotschi for letting us know about this issue and patiently wait for a fix.

**Closed by DavideD** 2022-01-14 09:39 UTC

**Comment by DavideD** [comment] 2022-01-14 09:55
I'm preparing a release now

**Comment by Sanne** [comment] 2022-01-14 10:50
@markusdlugi yes we'll upgrade Quarkus right away, it will be included in 2.7

**Comment by DavideD** [comment] 2022-01-14 10:51
I've started the release FIY

**Comment by DavideD** [comment] 2022-01-14 11:00
Hibernate Reactive `1.1.2.Final` is available. I've sent a PR for Quarkus: https://github.com/quarkusio/quarkus/pull/22898

**Comment by gavinking** [comment] 2022-01-14 11:56
Excellent, thanks for all your work on this @DavideD.
