### ISSUE TITLE
BlockingIdentifierGenerator invoked on wrong context under load

### ISSUE THREAD

**Issue by tsegismont** [hibernate/hibernate-reactive#1595] opened 2023-04-17 19:32 UTC
In `BlockingIdentifierGenerator`, when a new block is allocated, invocations of `generate` method are queued:

https://github.com/hibernate/hibernate-reactive/blob/75e57484d858bfc9e2d127d08b71ae4a5ad042b1/hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java#L94

After the result is received, queued tasks are executed:

https://github.com/hibernate/hibernate-reactive/blob/75e57484d858bfc9e2d127d08b71ae4a5ad042b1/hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java#L87

The problem is that they are executed on the Vert.x context which made the database call, not the context they were operating on when they were queued.

This explains the error logs in https://github.com/quarkusio/quarkus/issues/32533

**Comment by Sanne** [comment] 2023-04-17 20:06
Excellent, thanks for investigating!
Seems related to #1587 : the problem is different but for both of them we'll need safety tests under load.

**Comment by Sanne** [comment] 2023-04-23 20:17
Fixed now, thanks again @tsegismont - this was really tricky

**Closed** 2023-04-23 20:16 UTC

**Comment by tsegismont** [comment] 2023-05-02 13:20
You're welcome, I'm glad it helped
