### ISSUE TITLE
JoinColumns trouble

### ISSUE THREAD

**Issue by Xset-s** [hibernate/hibernate-reactive#342] opened 2020-09-01 13:48 UTC
Hello again, I continue researching your amazing library.
But today i got stuck with problem related to JoinColumns.

There are two entities:

SampleEntity:

```
@Entity
@Table(name = "sample_entities")
public class SampleEntity implements Serializable {
    @Id
    @Column(name = "first_key_id", nullable = false)
    public Long firstKeyId;

    @Id
    @Column(name = "second_key_id", nullable = false)
    public Long secondKeyId;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sampleEntity")
    public Set<SampleJoinEntity> sampleJoinEntities;
}
```

And SampleJoinEntity:

```
@Entity
@Table(name = "sample_join_entities")
public class SampleJoinEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "first_key_id", referencedColumnName = "first_key_id"),
            @JoinColumn(name = "second_key_id", referencedColumnName = "second_key_id")
    })
    public SampleEntity sampleEntity;
}
```

As you can see there is ManyToOne relation, which uses two keys. 

Let's try to persist them:

```
/* Working with SampleEntity */

final SampleEntity sampleEntity = new SampleEntity();

sampleEntity.firstKeyId = 1L;
sampleEntity.secondKeyId = 2L;

factory.withTransaction((session, transaction) -> session.persist(sampleEntity))
		.await().indefinitely();

/* Working with SampleJoinEntity */

final SampleJoinEntity sampleJoinEntity = new SampleJoinEntity();

sampleJoinEntity.sampleEntity = sampleEntity;

// ISSUE: IT THROWS EXCEPTION HERE!
factory.withTransaction((session, transaction) -> session.persist(sampleJoinEntity))
		.await().indefinitely();

```

When i m trying to persist sampleJoinEntity, hibernate throws this exception:

```
java.lang.UnsupportedOperationException: reactive persistence context
```

Full stack: https://pastebin.com/d68R7VpW

Sample project:
[JoinColumnsProject.zip](https://github.com/hibernate/hibernate-reactive/files/5156575/JoinColumnsProject.zip)

**Comment by DavideD** [comment] 2020-09-01 14:45
THanks, I'm having a look

**Comment by gavinking** [comment] 2020-09-01 15:13
I'm willing to bet that this is a result of #291, the issue I was asking for feedback on.

**Comment by gavinking** [comment] 2020-09-01 15:14
#210, I meant #210.

**Comment by DavideD** [comment] 2020-09-01 18:58
Not sure. The error in this case is related to `ReactivePersistenceContextAdapter#getDatabaseSnapshot()`.
I've converted the example @Xset-s provided into a testcase here: https://github.com/DavideD/hibernate-reactive/commit/d412c10a902d40674109d13ecf453fd738794797

I will have better look tomorrow.

**Comment by gavinking** [comment] 2020-09-01 21:57
> Not sure. The error in this case is related to `ReactivePersistenceContextAdapter#getDatabaseSnapshot()`.

My bet is it's being called from `StatefulPersistenceContext.getNaturalIdSnapshot()`.

**Comment by DavideD** [comment] 2020-09-03 13:57
I'm working on the fix for this issue but it seems that the problem is caused by the fact that `sampleEntity` is detached when you assigned it the second time. If you merge or refresh the value, it should work.

Example:
```
getMutinySessionFactory()
						.withTransaction( (session, tx) -> session.merge( sampleEntity )
								.invokeUni( merged -> {
									final SampleJoinEntity sampleJoinEntity = new SampleJoinEntity();
									sampleJoinEntity.sampleEntity = merged;
									return session.persist( sampleJoinEntity );
								} )
						).await().indefinitely();
```

**Closed** 2020-09-04 17:31 UTC
Labels: bug

**Comment by DavideD** [comment] 2020-09-04 17:33
Done!
