### ISSUE TITLE
AutoincrementTest fails on GitHub

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#136] opened 2020-05-19 19:20 UTC
https://github.com/hibernate/hibernate-reactive/runs/689901903

```
Gradle Test Executor 1 > org.hibernate.reactive.AutoincrementTest > testBasicTypes FAILED
    java.util.concurrent.CompletionException: io.vertx.pgclient.PgException: relation "basic" does not exist
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
...
        Caused by:
        io.vertx.pgclient.PgException: relation "basic" does not exist
            at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:29)
            at io.vertx.pgclient.impl.codec.PrepareStatementCommandCodec.handleErrorResponse(PrepareStatementCommandCodec.java:70)
```
On github we use the `docker` profile. This works for me locally with podman.

**Comment by DavideD** [comment] 2020-05-19 19:21
@gavinking, @aguibert Can you see if you have the same exception using docker, please? Thanks

**Comment by gavinking** [comment] 2020-05-19 19:41
With Docker, yes. Without Docker, no.

**Comment by gavinking** [comment] 2020-05-19 21:25
So here's the log:

```
alter table if exists Basic drop constraint if exists FKls5r2woctcukusfv91ds97irm
drop table if exists Basic cascade
create table Basic (id int8 generated by default as identity, binInteger varchar(255), bytes bytea, cover int4, date date, decimal numeric(19, 2), one varchar(255), two varchar(255), integer numeric(19, 2), _localDate date, _localDateTime timestamp, _localTime time, nullBoolean boolean, nullByte int2, nullDouble float8, nullFloat float4, nullInt int4, nullLong int8, primitiveBoolean boolean not null, primitiveByte int2 not null, primitiveDouble float8 not null, primitiveFloat float4 not null, primitiveInt int4 not null, primitiveLong int8 not null, string varchar(255), thing bytea, timeZone varchar(255), version int4, parent_id int8, primary key (id))
io.vertx.pgclient.PgException: syntax error at or near "generated"
alter table if exists Basic add constraint FKls5r2woctcukusfv91ds97irm foreign key (parent_id) references Basic
137834 INFO org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator  - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.JBossStandAloneJtaPlatform]
insert into Basic (binInteger, bytes, cover, date, decimal, one, two, integer, _localDate, _localDateTime, _localTime, nullBoolean, nullByte, nullDouble, nullFloat, nullInt, nullLong, parent_id, primitiveBoolean, primitiveByte, primitiveDouble, primitiveFloat, primitiveInt, primitiveLong, string, thing, timeZone, version) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28)
```

The problem seems to be the `generated by default as identity` clause.

Since that syntax is perfectly legal on current versions of Postgres, I wonder if the Docker image has an old version of Postgres.

WDYT, @aguibert?

**Comment by gavinking** [comment] 2020-05-19 21:32
The issue is really that without JDBC metadata we have no good way to determine the version of the database. Feature request for Vert.x?

**Comment by aguibert** [comment] 2020-05-19 21:32
Ah, that could be it. The PostgresContianer uses `postgres:9.6.12` by default. I specified a newer container label and now it works. I'll raise a PR shortly.

**Comment by gavinking** [comment] 2020-05-19 21:33
Great, thanks!

**Comment by aguibert** [comment] 2020-05-19 21:34
> The issue is really that without JDBC metadata we have no good way to determine the version of the database. Feature request for Vert.x?

Yea, definitely. What are the most important pieces of database metadata that are needed? Will DB major/minor version be sufficient for most cases?

**Comment by aguibert** [comment] 2020-05-19 21:36
Closing this item as a duplicate of #125

**Comment by gavinking** [comment] 2020-05-19 21:37
> Will DB major/minor version be sufficient for most cases?

Yup.

**Closed by aguibert** 2020-05-19 21:36 UTC

**Comment by aguibert** [comment] 2020-05-19 21:52
Raised an issue here: https://github.com/eclipse-vertx/vertx-sql-client/issues/645

@gavinking as you come across any other pieces of metadata that are needed, please add them to that issue

**Comment by gavinking** [comment] 2020-05-19 21:55
Thanks.
