### ISSUE TITLE
Tests end before closedb is completed

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#213] opened 2020-05-28 13:56 UTC
@gavinking After this commit https://github.com/hibernate/hibernate-reactive/commit/b35cb06d377b098216df47e9c2cec9fcc3f4c73a
if I launch `CompositeIdTest` from IntelliJ the `reactivePersist` test fails (`selectNameFromId` returns null).

Do you have the same issue?
@Sanne is this the failure you are having?

**Comment by DavideD** [comment] 2020-05-28 13:56
Note that it works if I build the project with gradle

**Comment by gavinking** [comment] 2020-05-28 13:58
Which db?

**Comment by DavideD** [comment] 2020-05-28 13:58
PostgreSQL

**Comment by gavinking** [comment] 2020-05-28 14:00
Can't reproduce. Stack trace?

**Comment by DavideD** [comment] 2020-05-28 14:01
There is not stacktrace, the test fails with:
```
Expected Tulip got null
java.lang.AssertionError: Expected Tulip got null
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:362)
```

**Comment by gavinking** [comment] 2020-05-28 14:02
Line number of the assertion?

**Comment by gavinking** [comment] 2020-05-28 14:05
Ah well wait.

If I check out that precise commit, I can reproduce the failure under certain circumstances: IntelliJ, no Docker.

But I could not reproduce it on current `master`.

**Comment by gavinking** [comment] 2020-05-28 14:11
I believe it's probably caused by one of the sessions in one of the other tests not being flushed.

**Comment by DavideD** [comment] 2020-05-28 14:11
I can  reproduce it consinstently, I will have a look

**Comment by gavinking** [comment] 2020-05-28 14:18
Closing the session seems to fix it. Which is weird, because I can't imagine *why*.

I mean, this is certainly more correct code:

```java
				openSession()
						.thenCompose( s -> s.persist( new GuineaPig( 10, "Tulip" ) ) )
						.thenCompose( s -> s.flush() )
						.thenAccept( s -> s.close() )
						.thenCompose( v -> selectNameFromId( 10 ) )
						.thenAccept( selectRes -> context.assertEquals( "Tulip", selectRes ) )
```

But why would not closing the session result in changes not being visible in the DB?

**Comment by DavideD** [comment] 2020-05-28 14:25
It still fails for me

**Comment by gavinking** [comment] 2020-05-28 14:25
¯\\\_(ツ)\_/¯

**Comment by DavideD** [comment] 2020-05-28 15:48
It should be fixed: https://github.com/DavideD/hibernate-reactive/commit/d5f6cd8a692c8d2f95931d515dc0914b8b2195e3

**Closed** 2020-05-28 15:49 UTC
