### ISSUE TITLE
@DynamicInsert not supported with IDENTITY columns

### ISSUE THREAD

**Issue by andrew-dzak** [hibernate/hibernate-reactive#939] opened 2021-08-11 20:19 UTC
project.ext.vertxVersion = '4.1.2'
project.ext.hibernateVersion = '1.0.0.CR9'

Database = (PostgreSQL) 13.2 (Debian 13.2-1.pgdg100+1).

This works fine in hibernateVersion = '1.0.0.CR7'. 
`public  static <T> T saveOrUpdate(T t){
        T entity = DatabaseConfiguration.getSessionFactory()
                .withTransaction((session,tx) ->  session.merge(t))
                .toCompletableFuture().join();
        return entity;
    }`

javax.persistence.PersistenceException: org.hibernate.HibernateException: java.lang.RuntimeException: Unable to obtain MySQLClient.LAST_INSERTED_ID field

**Comment by andrew-dzak** [comment] 2021-08-11 20:20
> project.ext.vertxVersion = '4.1.2'
> project.ext.hibernateVersion = '1.0.0.CR9'
> 
> Database = (PostgreSQL) 13.2 (Debian 13.2-1.pgdg100+1).
> 
> This works fine in hibernateVersion = '1.0.0.CR7'.
> `public static <T> T saveOrUpdate(T t){ T entity = DatabaseConfiguration.getSessionFactory() .withTransaction((session,tx) -> session.merge(t)) .toCompletableFuture().join(); return entity; }`
> 
> javax.persistence.PersistenceException: org.hibernate.HibernateException: java.lang.RuntimeException: Unable to obtain MySQLClient.LAST_INSERTED_ID field

**Comment by gavinking** [comment] 2021-08-16 19:30
@andrew-dzak could you please show us the wrapped exception? It should be the next line of the stack trace.

@Sanne what do you make of this one? Classloader issue, perhaps?

@andrew-dzak what is the environment? Quarkus? Something else?

**Comment by andrew-dzak** [comment] 2021-08-16 19:50
@gavinking  environment
 vertx version =4.1.2 
hibernate reactive ='1.0.0.CR9'
Database  = (PostgreSQL) 13.2 (Debian 13.2-1.pgdg100+1).

**Comment by gavinking** [comment] 2021-08-16 20:07
No but what is this executing in I mean?

**Comment by andrew-dzak** [comment] 2021-08-17 06:32
@gavinking   hope this helps.   when i change the hibernate reactive version to 1.0.0.CR7 same code persist fine without exceptions

`  EventTicketCategory ticketCategory =EventTicketCategory.newEventTicketCategory(category.getTitle(),event,category.getPrice(),startDateTime,
                    endDateTime,referenceCode,category.getDescription(),category.getNumberOfTickets(),category.getDiscount(),fee);

            **EventTicketCategory ev = DAOUtils.saveOrUpdate(ticketCategory);**
            handler.reply(new JsonObject().put("id",ev.getId()));
        }catch (Exception e){
            handler.reply(new JsonObject(new DBExceptionErrors(e,e.getMessage()).toString()));
            return;
        }`

` public  static <T> T saveOrUpdate(T t){
        T entity = **DatabaseConfiguration.getSessionFactory()**
                .withTransaction((session,tx) ->  session.merge(t))
                .toCompletableFuture().join();
        return entity;

    }`

`
    public DatabaseConfiguration() {
        emf = Persistence.createEntityManagerFactory("ticketing-pu");
        sessionFactory =emf.unwrap(Stage.SessionFactory.class);
    }

    public static Stage.SessionFactory getSessionFactory() {
        return sessionFactory;
    }`

**Comment by gavinking** [comment] 2021-08-25 10:34
Well, look, I think they best way to proceed is for you to produce a very simple isolated and easily-runnable test that reproduces the issue.

Because I certainly can't reproduce the error, and I can't think of any reason why that code would be called on Postgres.

I *suspect* that you have something rather strange in your Hibernate configuration, but who knows?

**Comment by Sanne** [comment] 2021-08-25 11:54
> @Sanne what do you make of this one? Classloader issue, perhaps?

FWIW I would be surprised if a Classloader issue would trigger this - but hard to say with certainty.

+1 for the need to see a reproducer.

**Comment by gavinking** [comment] 2021-09-04 19:31
Hi, @andrew-dzak, we’re going to need a runnable test case, or I’m going to close this issue.

**Comment by andrew-dzak** [comment] 2021-09-06 06:03
@gavinking  sorry was on vacation will try and get a test case before close of day

**Comment by gavinking** [comment] 2021-09-06 08:06
OK, sure, thanks.

**Comment by andrew-dzak** [comment] 2021-09-06 09:34
@gavinking  @Sanne 

Hi had to put something quickly on this one 
 test case is on  https://github.com/andrew-dzak/testcase.  repository is public 
let me know if this is enough

**Comment by gavinking** [comment] 2021-09-06 10:27
The problem is related to `@DynamicInsert`, and can be reproduced with a *much* simpler test.

Look, it would have been really great if you would have taken the time to *isolate* the problem before reporting it. It's really very easy to do that: just remove code until the problem goes away, and then the last bit of code you removed gives you a strong hint about the true nature of the problem,  allowing you to write *much* better issue reports. 

Your issue report mentions *nothing* about `@DynamicInsert`, and so we had literally *no way* to find the bug from what you gave us.

**Comment by andrew-dzak** [comment] 2021-09-06 10:35
@gavinking  thanks sure will do that next time in reporting any new issue.  Should have added the domain class when reporting this .

**Comment by gavinking** [comment] 2021-09-06 10:39
Thanks.

**Comment by gavinking** [comment] 2021-09-06 10:49
I believe that #958 fixes this. We copy/pasted some code from ORM core that is sorta wrong.

**Closed** 2021-09-06 16:13 UTC
Labels: bug

**Comment by gavinking** [comment] 2021-09-06 16:15
I also fixed it so that we won't get this confusing error message in case of future bugs.
