### ISSUE TITLE
HR000057: Failed to execute statement [query output ] $2could not execute query Caused by: java.lang.IllegalStateException: Session/EntityManager is closed

### ISSUE THREAD

**Issue by andrew-dzak** [hibernate/hibernate-reactive#1246] opened 2022-03-16 18:51 UTC
Replicate : Find two entities with multiples api calls will result in this error. Single call is all fine.
hibernate reactive version =1.1.3.Final
vertx version = 4.2.4

```
Future<Role> role = DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params);
Future<Role> role2 = DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params);`
```

```
public static <T> Future<T> findSingleEntityByQuery(Class<T> clazz, String hql, Map<String,Object> params){
        return Future.fromCompletionStage(DatabaseConfiguration.getSessionFactory().withSession(session -> {
            Stage.Query<T>  query = session.createQuery(hql,clazz);

            if(params != null && !params.isEmpty()){
                params.keySet().stream().forEach(key ->
                        query.setParameter(key,params.get(key)));
            }

            return query.getSingleResultOrNull();
        }).toCompletableFuture());

    }
```

I might be doing something stupid lol

**Comment by DavideD** [comment] 2022-03-16 19:05
I don't see anything wrong with `findSingleEntityByQuery` (but I don't think you need the `.toCompletableFuture())`.
Is it possible that  are not closing the `SessionFactory` before the query have finished?

**Comment by andrew-dzak** [comment] 2022-03-16 19:12
> I don't see anything wrong with `findSingleEntityByQuery` (but I don't think you need the `.toCompletableFuture()`). Is it possible that are not closing the `SessionFactory` before the query have finished?

@DavideD  took this part out toCompletableFuture() still getting the same error

**Comment by DavideD** [comment] 2022-03-16 19:16
I think some operations you are running are not happening in the right order.

I don't think I can help you without a reproducer or looking at the code in your project.

Make sure that the session factory is not closed before the future have finished. Otherwise I don't understand how you could see this error.

**Comment by DavideD** [comment] 2022-03-16 19:22
I mean, what's happening after you have `role` and `role2`?

**Comment by andrew-dzak** [comment] 2022-03-16 19:34
> I mean, what's happening after you have `role` and `role2`?


`
public static Future<RoleData> getRole(final RoutingContext rc){
        final Long roleId = Long.parseLong(rc.pathParam("id"));
        Promise<RoleData> promise = Promise.promise();
        Map<String,Object> params = new HashMap<>();
        params.put("roleId", roleId);

        Future<Role> role = DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params);
        //to replicate issue not needed in code
        Future<Role> role2 = DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params);

        role.compose(r -> Future.succeededFuture(RoleData.toRoleData(r)))
                .onSuccess(promise::complete)
                .onFailure(f ->ResponseUtils.buildEntityNotFoundResponse(rc,"role",roleId));
        return promise.future();
    }
`

i just return the  data. Weird thing is the first API call i do not get the error. Only on the second call 
I think you should able able to replicate on your example on 
https://github.com/DavideD/jbang-rep/blob/d58be92c49d6fbca431b172ba1bc210c78f307bb/StageVerticle.java#L144
by call the getProduct() function twice

**Comment by andrew-dzak** [comment] 2022-03-16 20:10
@DavideD  interesting find  changing withSession to withTransaction for testing purpose. The error does not show 

```
public static <T> Future<T> findSingleEntityByQuery(Class<T> clazz, String hql, Map<String,Object> params){
        return Future.fromCompletionStage(DatabaseConfiguration.getSessionFactory().withTransaction(session -> {
            Stage.Query<T>  query = session.createQuery(hql,clazz);

            if(params != null && !params.isEmpty()){
                params.keySet().stream().forEach(key ->
                        query.setParameter(key,params.get(key)));
            }
            return query.getSingleResultOrNull();
        }));

    }
```

**Comment by DavideD** [comment] 2022-03-16 21:26
I think this is what's happening:
while `role2` is executing the query, the test finishes and closes the session factory causing the error.

This should work:
```
return CompositeFuture.all( role, role2 ).compose( ignore -> role).compose( ... );
```

**Comment by DavideD** [comment] 2022-03-16 21:27
Assuming the `getSessionFactory()` returns the same factory each time

**Comment by DavideD** [comment] 2022-03-16 21:31
> @DavideD interesting find changing withSession to withTransaction for testing purpose. The error does not show

Interesting but not something we can rely on. It's possible that when you use `.withTransaction` things are a bit slower and everything happens in the right order

**Comment by DavideD** [comment] 2022-03-16 21:33
To begin with, is this an integration test? Are you actually closing the session factory at some point? What's happening in `getSessionFactory`?

**Comment by andrew-dzak** [comment] 2022-03-16 21:54
> To begin with, is this an integration test? Are you actually closing the session factory at some point? What's happening in `getSessionFactory`?

NO

```
public class DatabaseConfiguration  implements  DatabaseAccess {

    private static EntityManagerFactory emf;
    private  static Stage.SessionFactory sessionFactory;

    public void startHibernates(Promise<Void> promise) {
        try{
            emf = Persistence.createEntityManagerFactory("agro-pu");
            sessionFactory = emf.unwrap(Stage.SessionFactory.class);
            promise.complete();
        }catch (Exception e){
            promise.fail(e.getMessage());
        }
    }

    public static Stage.SessionFactory getSessionFactory() {
        return sessionFactory;
    }
```

**Comment by DavideD** [comment] 2022-03-16 21:59
Mmmh.... OK, I will try to write a test for this and see what happens

**Comment by andrew-dzak** [comment] 2022-03-16 22:00
> Mmmh.... OK, I will try to write a test for this and see what happens

OK thanks let me know how it goes

**Comment by DavideD** [comment] 2022-03-16 22:03
> I might be doing something stupid lol

By the way, this stuff is hard, there are no stupid questions.

**Comment by andrew-dzak** [comment] 2022-03-21 11:46
@DavideD  so when i initialize hibernate outside the context of vertx. 
`
INFO: HR000002: Vert.x not detected, creating a new instance
`
Same code i do not get the error.  maybe this might help in fixing the issue

**Comment by DavideD** [comment] 2022-03-23 11:50
I think the cause of the error is that `withSession` will create a new session [only if one doesn't exist already in the current Vert.x context.](https://github.com/hibernate/hibernate-reactive/blob/cda2cfe64c2bccd93550f0302910e1672fa5aea1/hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java#L151).

When you run the two methods:
```
Future<Role> role = DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params);
 //to replicate issue not needed in code
 Future<Role> role2 = DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params);
```

They will end up using the same session but one finishes before the other, closing the session when the other is still using it.
I would recommend to check if the two calls use the same session.

Using the session factory in a different Vert.x  instance than the one you are running the app shouldn't be necessary (and I don't think it solves this issue).

**Comment by andrew-dzak** [comment] 2022-03-23 12:54
@DavideD  so on the first call to the API end-point.  Both the calls 
```
Future<Role> role = DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params);
 //to replicate issue not needed in code
 Future<Role> role2 = DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params);
```
it uses a new session 
`LOG.debug( "No existing open Stage.Session was found in the current Vert.x context: opening a new instance" );
			return withSession( openSession(), work, contextKeyForSession );
`
on the second time i make the api call . It uses the the current session 
`
LOG.debug( "Reusing existing open Stage.Session which was found in the current Vert.x context" );
			return work.apply( current );
`
Using the session factory in a different Vert.x instance than the one you are running the app shouldn't be necessary (and I don't think it solves this issue).

Not planning to use that as a solution but i notice when i initialize the Database outside the vertx context.  Am not able to reproduce the error with the same calls

**Closed** 2022-03-23 13:42 UTC

**Comment by andrew-dzak** [comment] 2022-03-24 18:16
@DavideD  
````
role.compose(v ->  DatabaseUtils.findSingleEntityByQuery(Role.class,AppUserRepository.FIND_ROLE_WITH_PERMISSION,params)) ````

works so for now will refactor the code in this way. 

Using the session factory in a different Vert.x instance than the one you are running the app shouldn't be necessary (and I don't think it solves this issue). It actually does solve the problem and i don't get the error when i make parallel calls.
